# Generated by Django 5.0.7 on 2024-11-04 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_replyreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='replyreview',
            name='city',
        ),
        migrations.AddField(
            model_name='replyreview',
            name='review',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='reviews.reviews'),
        ),
    ]
